### ISSUE TITLE
Provide clearer explanation of the innards of `MeshSeq` and its subclasses

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus#122]
Raised by @ddundo.

**Comment by jwallwork23** [comment]
If your time partition has multiple subintervals then surely it is unsteady, no? Could you not solve the problem using a single subinterval?

Please could you either elaborate or provide a minimum failing example? i.e., a (preferably short) snippet of code which exhibits the issue you mention.

I would prefer to keep the current behaviour of raising an error rather than a warning, if possible.

**Comment by jwallwork23** [comment]
@ddundo Do you have any updates on this?

**Comment by ddundo** [comment]
Hey @jwallwork23 , sorry for being slow with this - I've been tempted to just close it after failing to find a simpler example than mine (although I can imagine there being many cases). But here is a clearer explanation of my specific case:

In my `get_solver` I've got two equations: a time-dependent one for ice thickness (mass conservation) and a time-independent, diagnostic equation for ice velocity (depth-averaged Stokes). I first solve the time-dependent equation for thickness and then compute the ice velocity based on that new thickness field. The output is both those fields. So it is an unsteady problem and the `thickness` field has the dependency `thickness_old` but the `velocity` field has no dependencies - hence the Error above.

I imagine there are other cases where this would raise the same error. Generally something like solving a time-dependent equation for some background field and then computing another domain-wide property field based on that background field at each timestep. I don't know :) I'm working around this in my case, so please feel free to close if you think it's not relevant.

**Comment by jwallwork23** [comment]
It’s okay, no pressure! Was just wondering if I could help. So is the time independent equation just solved once at the very end, based on the final solution of the time dependent equation? Or is it solved at multiple time steps based on the intermediate time dependent solutions?

**Comment by ddundo** [comment]
Thanks Joe :) the time-independent equation (for velocity) is solved at each timestep, after solving the time-dependent one (for thickness). Thickness is a function of velocity here.

**Comment by stephankramer** [comment]
Just to clarify: I think we are talking about solving equations without a time derivative. They are still time-dependent in the sense that they depend on _other_ fields that are time-dependent and have been previously solved for - it's just that they don't depend on the previous value of the field that's solved for in that equation.

Some other examples of where this might happen:
* mantle convection modelling: each timestep you solve a steady-state Stokes system (so it doesn't depend on previous values of u and p) but it does depend on temperature in the buoyancy. The velocity that comes out is then used in a normal time-dependent advection-diffusion equation for temperature, which will feed into the Stokes solve in the next timestep solve
* when you do a continuous pressure projection approach: you timestep the momentum equation forward for a preliminary velocity, but then you solve a pressure equation whose right-hand side does depend on that preliminary velocity but the pressure equation does not depend on the previous value of p

**Comment by ddundo** [comment]
Exactly, thanks for that Stephan!
