### ISSUE TITLE
Naming/renaming adapted meshes (for checkpointing)

### ISSUE THREAD

**Issue by ddundo** [pyroteus/pyroteus#129]
Hey! Probably a question related to `firedrake.meshadapt`: is it possible to somehow rename a mesh, or to give it a new name in during checkpointing? We can name functions while checkpointing with `save_function(fn, name='fn_name')` but I don't think it works for meshes.

My solution for this was to add a naming argument in `firedrake.meshadapt.adapt` and then modify [this line](https://github.com/firedrakeproject/firedrake/blob/a0d36cb9f784aae8e9b8c4d64c8cc9a1a0e7a04c/firedrake/meshadapt.py#L444):

```python
    return fmesh.Mesh(newplex, distribution_parameters={"partition": False}, name=name)
```

If there isn't a better way to do this, could we add this option in `meshadapt.adapt`?

**Comment by jwallwork23** [comment]
Done. See https://github.com/firedrakeproject/firedrake/pull/2796/commits/e296528d1c7e86c135b80db1bc4cbffd6893f56e.

**Comment by ddundo** [comment]
Thanks @jwallwork23!

**Comment by ddundo** [comment]
Hey again! I think we need to make one more change here. Let's say we adapt and checkpoint a mesh

```python
amsh = adapt(initial_mesh, metric, name='adapted_mesh')
with CheckpointFile(outfile, 'w') as afile:
    afile.save_mesh(amsh)
```

We will then have two topology paths in the `outfile` contents: one `/topologies/adapted_mesh/`and another that comes from the PETSc DM mesh topology representation `amsh.topology_dm.name`, which will be something like `/topologies/DM_0x84000003_1/`. This usually won't cause issues since the numbering/suffix would change automatically (`DM_..._1`, `DM_..._3`, etc.), but it always starts from 1 when a script is run again. In that case, if we want to append to the checkpoint file, it would raise an error saying that the mesh under that name already exists. I encountered this because I am running my adapt script in serial, from inside the usual script where I run my simulation in parallel.

I didn't want to dig too much into PETSc and what exactly and at what stage should be renamed, but my hacky solution which works is to add a line `newplex.name = self.name` in [firedrake.mesh_adapt.adapted_mesh](https://github.com/firedrakeproject/firedrake/blob/437e32bd876d1465efb2aa743da522b9d6068939/firedrake/meshadapt.py#L437). Then the checkpoint file looks as it should (with only the `/topologies/adapted_mesh/` path) and doesn't cause issues. I can dig a bit more into this soon or if you're happy with the hacky solution, we could just do that :)

**Comment by jwallwork23** [comment]
Hi @ddundo. Please could you close this issue and open a new one for it in https://github.com/pyroteus/animate/issues? That's where this stuff is going to live now.
