### ISSUE TITLE
Time-dependent Hessian-based mesh adaptation demo

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus#137]
Parent: #94.

Just consider the Burgers demo with a space-time-normalised Hessian-based metric.

**Comment by ddundo** [comment]
Hey @jwallwork23 , have you maybe made a start on this please? I am curious if you came across any issues with `metric.space_time_normalise` while doing this or testing previously, after my commit 5501aa30328b6d7df18bafadd533271776718dbe . Sometimes I get new metric complexities which are 2 orders of magnitude lower than the set target complexities, and sometimes they agree quite well. So when I encounter this I'd just increase my target complexity to get the desired number of DoF's. And the meshes do look great!

Could you tell me what you make of this please? Is this to be expected sometimes (why?)? I'm not sure if I messed something up in the commit mentioned above, in my adaptor function, or if there isn't an issue at all. So I'd be very curious to see an example of your adaptor function and how you combine metrics and normalise them. Here is a very simple example of mine which gives me the above behaviour:

```python
mp = {
    "dm_plex_metric_target_complexity": 1e6,
    "dm_plex_metric_h_min": 1.,
    "dm_plex_metric_h_max": 50e3,
    "dm_plex_metric_p": 2,
    "dm_plex_metric_a_max": 1e5,
}

def adaptor_hessian(mesh_seq, solutions):
    metrics = []
    for i in range(len(mesh_seq)):
        P1_tensor = TensorFunctionSpace(mesh_seq[i], "CG", 1)
        temp_metrics = [RiemannianMetric(P1_tensor) for _ in solutions.u.forward[i]]
        for j, u_sol in enumerate(solutions.u.forward[i]):
            temp_metrics[j].compute_hessian(u_sol)
        metrics.append(combine_metrics(*temp_metrics, average=True))

    metrics = space_time_normalise(metrics, time_partition, mp, restrict_sizes=True, restrict_anisotropy=True)

    for i in range(len(mesh_seq)):
        mesh_seq[i] = adapt(mesh_seq[i], metrics[i])

    return True
```

I'm happy to test this further if needed. In which case, do you maybe have an older example that you're confident is correct that I could play around with and try to replicate the results?

**Comment by jwallwork23** [comment]
Hi @ddundo. Okay, I will look into this issue next.
