### ISSUE TITLE
Solution transfer

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus#8]
To implement (in parallel):

- [x] Clement interpolation
- [ ] Consistent interpolation

To hook up:

- [ ] Parallel supermesh projection

**Comment by ddundo** [comment]
Hei @jwallwork23, has there been some progress here with parallel supermesh projection? :)

**Comment by jwallwork23** [comment]
> Hei @jwallwork23, has there been some progress here with parallel supermesh projection? :)

I'm afraid not, no. I did some work on implementing consistent interpolation towards the end of my postdoc but there was still a long way to go.

In theory you can use the existing supermesh projection in parallel already, but you need to make sure that the distribution parameters match between source and target meshes.  See tests here for examples: https://github.com/firedrakeproject/firedrake/tree/master/tests/supermesh.
